### ISSUE TITLE
Need a way to report build and jdk info after ci test

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-arquillian-managed#19]
Since this guide doesn't generate the `console.log`, the usual way to get the build and jdk info after the ci test doesn't work. Need to find another way to do this. 

cat target/liberty/wlp/usr/servers/ArquillianManagedServer/logs/
messages.log  state/        
evelines-mbp:finish evelinec$ cat target/liberty/wlp/usr/servers/ArquillianManagedServer/logs/messages.log 
********************************************************************************
product = Open Liberty 18.0.0.4 (wlp-1.0.23.cl180420181121-0300)
wlp.install.dir = /Users/evelinec/OLG/testing/temp/draft-guide-arquillian-managed/finish/target/liberty/wlp/
java.home = /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
java.version = 1.8.0_151
java.runtime = Java(TM) SE Runtime Environment (1.8.0_151-b12)
os = Mac OS X (10.13.3; x86_64) (en_CA)

**Comment by gkwan-ibm** [comment]
close
- already fixed when migrate test to use Github action
