### ISSUE TITLE
tools.jar 1.6

### ISSUE THREAD

**Issue by javabean68** [OpenLiberty/guide-arquillian-managed#59]
Hi,

I'm trying your example on the arquillian Integration but something seems wrong after importing the Project in Eclipse. I get the maven error:

Missing artifact com.sun.tools.jar 1.6.0 with scope System. If I see  in the dependency tree pom.xml dependencies I find it comes through:

arquillian-liberty-managed-junit: 1.1.3 [test]
| 
|----arquilian-liberty-managed: 1.0.3 [test]

What am I doing wrong or do you have to correct something? 

Thank you for help.
Bye

**Comment by andrewdes** [comment]
Hello @javabean68,

What version of Java and what version of Maven are you using?

**Comment by chyt** [comment]
Hi, can you make sure that your Eclipse configuration is pointing to the JDK and not the JRE? The `tools.jar` is only available in the JDK.

**Comment by javabean68** [comment]
H Charles,
Thank you for your email.

Te maven Project compiles without Problems. I find it very nice as all the
other example in this openliberty.io site.
The only Problem I noticed is with eclipse:
[image: image.png]
that's to say:
[image: image.png]
[image: image.png]

I'm using the JDK 1.8, Maven 3.3.9, eclipse-jee-2018-09-> the dependency is
how already said a System dependency and Comes from an arquillian liberty
pom. I have no JDK 1.6 on my machine.

Many thanks
Regards
Fabio



Am Mo., 18. März 2019 um 19:09 Uhr schrieb Charles Y. Tian <
notifications@github.com>:

**Comment by yeekangc** [comment]
@javabean68, the images didn't attach properly.  Can you please re-post?

Tagging @gkwan-ibm so he is aware of this issue.

**Comment by javabean68** [comment]
Hi

sorry. I replied by email and die images weren't properly posted.

If I exclude the imported dependency is the Problem with eclipse away

Thanks 
Regards
Fabio

**Comment by javabean68** [comment]
![Unbenannt03](https://user-images.githubusercontent.com/25293663/54604174-6d188380-4a46-11e9-81d8-60cf45e2db0e.PNG)
![Unbenannt02](https://user-images.githubusercontent.com/25293663/54604307-bb2d8700-4a46-11e9-8bba-ab1d98222357.PNG)

**Comment by chyt** [comment]
I don't think the version `1.6` should matter if it is a system dependency. Are you using Windows or Mac? Can you verify that the location of the `tools.jar` in your JDK matches what the system dependency is trying to reference? We are looking for the JAR in `${java.home}/../lib/tools.jar`. For example, here is the location on my machine (JDK 1.8.0_131, Eclipse JEE 4.7.2, Maven 3.3.9):

<img width="869" alt="Screen Shot 2019-03-19 at 10 47 08 AM" src="https://user-images.githubusercontent.com/3202957/54620560-5b2de500-4a34-11e9-89b5-9fa922f3965f.png">

**Comment by chyt** [comment]
Also I'm confused how you are able to resolve the problem by excluding the `tools.jar` dependency. It is required in order to allow Arquillian to connect to the running Liberty server.

**Comment by javabean68** [comment]
Hi Charles

Couldn't be referenced a generic Tools.jar instead of the 1.6 one? Perhaps
giving the Version as property...

Bye
Fabio

Charles Y. Tian <notifications@github.com> schrieb am Di. 19. März 2019 um
17:17:

**Comment by chyt** [comment]
Hi, as I said before I don't believe the version should matter. The dependency is referenced through the file system, so if the file exists in the path given by the `systemPath` parameter (`${java.home}/../lib/tools.jar`), then it should be resolved. I'm not exactly sure of the history of why that version is there, but I can look into it more. In the meantime could you please address my questions above?

**Comment by javabean68** [comment]
Hi Charles,
 you're right. It muss be an issue with Eclipse/JRE/JDK on Windows.

On Linux with Intellij I found no problems. Much ado for nothing! Sorry!!
It's the first time I see tool.jar explicitly referenced and I didn't
understand why. Thanks für the explanation.

Only another question. Why has the POJO SystemClient which is injected in
the @ApplicationScoped InventoryManager the Scope @RequestScoped? I would
have expected @Default...
Thank you for your time!
Regards
Fabio

Am Di., 19. März 2019 um 21:27 Uhr schrieb Charles Y. Tian <
notifications@github.com>:

**Comment by javabean68** [comment]
I would have expected @Dependent

Time to go to sleep :-)

Am Di., 19. März 2019 um 22:59 Uhr schrieb Fabio Salvi <safesfabio@gmail.com

**Comment by yeekangc** [comment]
Re SystemClient, yes, that's an issue, @javabean68.  We are addressing with https://github.com/OpenLiberty/guide-cdi-intro/issues/82.

**Comment by chyt** [comment]
Glad to help. Closing now, if you have any other unrelated follow-up questions feel free to open another issue.
