### ISSUE TITLE
Unresolved directive in README.adoc

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-arquillian-managed#67]
The published guide shows the below under "What you'll learn"

"Unresolved directive in README.adoc - include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/gitclone.adoc[]"

**Comment by MaiHameed** [comment]
Same issue in the Maven guide, here: https://github.com/OpenLiberty/guide-maven-intro/issues/76

**Comment by cherylking** [comment]
This is the standard directive for the git clone command in all the guides. Not a problem specific to this guide I think.

**Comment by MaiHameed** [comment]
Fixed, closing.
