### ISSUE TITLE
Enable allowConnectingToRunningServer option

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-arquillian-managed#69]
In order to run this guide in dev mode (and since dev mode starts the app server), arquillian tests can be configured with the `allowConnectingToRunningServer` flag to connect to the running server and then run the test. Currently, this guide doesn't have this content. This issue is to determine whether to include this new content. 

Step to run in dev mode:
1. Add the <allowConnectingToRunningServer>true</allowConnectingToRunningServer> property to the pom.xml
2. On a command prompt, run mvn liberty:dev
3. On another command prompt, run mvn liberty:configure-arquillian
4. On the dev mode prompt, press enter to run the tests

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/ci.maven/issues/848

**Comment by gkwan-ibm** [comment]
this issue will fix issue #93

**Comment by gkwan-ibm** [comment]
close
- updated the guide
