### ISSUE TITLE
Usage clarifications

### ISSUE THREAD

**Issue by tsobe** [OpenLiberty/guide-arquillian-managed#91]
Hello, please clarify the following items:
1. is it really needed to invoke liberty:deploy goal? Isn't Arquillian supposed to manage the deployment automatically? 
2. actually 2 web modules are being deployed here, one is _guide-arquillian-managed_ (as configured in server.xml) and the second - _arquillian-managed_ (as specified in the ShrinkWrap). What is the intention here? Initially I thought, maybe the former is supposed to contain only "production classes" and later only "test classes", but clearly that's not the case, the later includes classes from the production package, so doesn't it duplicate the deployment (in a different module) that is already done by liberty:deploy goal? If I omit manual invocation of this goal, then test fails with _expected:<200> but was:<500>_ (and I cannot locate server logs to find what actually happened)

**Comment by yeekangc** [comment]
Thank you, @tsobe.  We are investigating the issues.

@gkwan-ibm @kathrynkodama

**Comment by gkwan-ibm** [comment]
hi @tsobe,

1. Yes, you are right that it is not necessary to invoke `liberty:deploy` goal. We will fix the guide and the application.
2. guide-arquillian-managed.war is generated by `liberty:deploy` which is for production. arquillian-managed.war is generated by the test. 

The fix will work no matter the `liberty:deploy` goal is run or not.

**Comment by gkwan-ibm** [comment]
close
- the guide was updated
