### ISSUE TITLE
Add a "Try what you'll build" to the "Getting Started" section

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/guide-arquillian-managed#93]
In other guides there is a "Try what you'll build" section to try out the finish directory before starting the guide. See https://openliberty.io/guides/rest-intro.html#try-what-youll-build 

We should add this section to the Arquillian guide for consistency.

**Comment by gkwan-ibm** [comment]
It will be reconsidered when `liberty:dev` or `liberty:run` can support arquillian better

**Comment by gkwan-ibm** [comment]
close
- this issue will be fixed by #69
